CATALOGO = {
    "accion": [
        {"titulo": "Naruto", "slug": "naruto-clasico"},
        {"titulo": "Naruto Shippuden", "slug": "naruto-shippuden"},
        {"titulo": "Attack on Titan", "slug": "shingeki-no-kyojin"},
        {"titulo": "Demon Slayer", "slug": "kimetsu-no-yaiba"},
        {"titulo": "Dragon Ball Z", "slug": "dragon-ball-z"},
        {"titulo": "Dragon Ball Super", "slug": "dragon-ball-super"},
        {"titulo": "Bleach", "slug": "bleach"},
        {"titulo": "One Punch Man", "slug": "one-punch-man"},
        {"titulo": "My Hero Academia", "slug": "boku-no-hero-academia"},
        {"titulo": "Fullmetal Alchemist Brotherhood", "slug": "fullmetal-alchemist-brotherhood"},
        {"titulo": "Hunter x Hunter", "slug": "hunter-x-hunter-2011"},
        {"titulo": "Jujutsu Kaisen", "slug": "jujutsu-kaisen"},
        {"titulo": "Black Clover", "slug": "black-clover"},
        {"titulo": "Fairy Tail", "slug": "fairy-tail"},
        {"titulo": "Tokyo Revengers", "slug": "tokyo-revengers"},
        {"titulo": "Chainsaw Man", "slug": "chainsaw-man"},
        {"titulo": "Vinland Saga", "slug": "vinland-saga"},
        {"titulo": "Sword Art Online", "slug": "sword-art-online"},
        {"titulo": "Gurren Lagann", "slug": "tengen-toppa-gurren-lagann"},
        {"titulo": "Mob Psycho 100", "slug": "mob-psycho-100"},
    ],
    "romance": [
        {"titulo": "Toradora", "slug": "toradora"},
        {"titulo": "Sword Art Online", "slug": "sword-art-online"},
        {"titulo": "Your Lie in April", "slug": "shigatsu-wa-kimi-no-uso"},
        {"titulo": "Clannad", "slug": "clannad"},
        {"titulo": "Clannad After Story", "slug": "clannad-after-story"},
        {"titulo": "Fruits Basket", "slug": "fruits-basket-2019"},
        {"titulo": "Kaguya-sama: Love is War", "slug": "kaguya-sama-wa-kokurasetai"},
        {"titulo": "Oregairu", "slug": "yahari-ore-no-seishun-love-comedy-wa-machigatteiru"},
        {"titulo": "Nisekoi", "slug": "nisekoi"},
        {"titulo": "Horimiya", "slug": "horimiya"},
        {"titulo": "Quintessential Quintuplets", "slug": "go-toubun-no-hanayome"},
        {"titulo": "Rent-a-Girlfriend", "slug": "kanojo-okarishimasu"},
        {"titulo": "ReZero", "slug": "re-zero-kara-hajimeru-isekai-seikatsu"},
        {"titulo": "Ano Hi Mita Hana", "slug": "ano-hi-mita-hana-no-namae-wo-bokutachi-wa-mada-shiranai"},
        {"titulo": "Karakai Jouzu no Takagi-san", "slug": "karakai-jouzu-no-takagi-san"},
        {"titulo": "Bloom Into You", "slug": "yagate-kimi-ni-naru"},
        {"titulo": "Wotakoi", "slug": "wotaku-ni-koi-wa-muzukashii"},
        {"titulo": "Tada Never Falls in Love", "slug": "tada-kun-wa-koi-wo-shinai"},
        {"titulo": "Ouran High School Host Club", "slug": "ouran-koukou-host-club"},
        {"titulo": "Lovely Complex", "slug": "lovely-complex"},
    ],
    "comedia": [
        {"titulo": "Konosuba", "slug": "kono-subarashii-sekai-ni-shukufuku-wo"},
        {"titulo": "Gintama", "slug": "gintama"},
        {"titulo": "Nichijou", "slug": "nichijou"},
        {"titulo": "Grand Blue", "slug": "grand-blue"},
        {"titulo": "Gekkan Shoujo Nozaki-kun", "slug": "gekkan-shoujo-nozaki-kun"},
        {"titulo": "Shimoneta", "slug": "shimoneta-to-iu-gainen-ga-sonzai-shinai-taikutsu-na-sekai"},
        {"titulo": "Prison School", "slug": "prison-school"},
        {"titulo": "Saiki K.", "slug": "saiki-kusuo-no-psi-nan"},
        {"titulo": "Cromartie High School", "slug": "sakigake-cromartie-koukou"},
        {"titulo": "Daily Lives of High School Boys", "slug": "danshi-koukousei-no-nichijou"},
        {"titulo": "One Punch Man", "slug": "one-punch-man"},
        {"titulo": "Kaguya-sama: Love is War", "slug": "kaguya-sama-wa-kokurasetai"},
        {"titulo": "Overlord", "slug": "overlord"},
        {"titulo": "Isekai Quartet", "slug": "isekai-quartet"},
        {"titulo": "Pop Team Epic", "slug": "pop-team-epic"},
        {"titulo": "Haven't You Heard? I'm Sakamoto", "slug": "sakamoto-desu-ga"},
        {"titulo": "Gabriel DropOut", "slug": "gabriel-dropout"},
        {"titulo": "Asobi Asobase", "slug": "asobi-asobase"},
        {"titulo": "Himouto Umaru-chan", "slug": "himouto-umaru-chan"},
        {"titulo": "Yuru Camp", "slug": "yuru-camp"},
    ],
    "terror": [
        {"titulo": "Another", "slug": "another"},
        {"titulo": "Higurashi", "slug": "higurashi-no-naku-koro-ni"},
        {"titulo": "Elfen Lied", "slug": "elfen-lied"},
        {"titulo": "Parasyte", "slug": "kiseijuu-sei-no-kakuritsu"},
        {"titulo": "Corpse Party", "slug": "corpse-party-tortured-souls"},
        {"titulo": "Shiki", "slug": "shiki"},
        {"titulo": "Hellsing Ultimate", "slug": "hellsing-ultimate"},
        {"titulo": "The Promised Neverland", "slug": "yakusoku-no-neverland"},
        {"titulo": "Deadman Wonderland", "slug": "deadman-wonderland"},
        {"titulo": "Tokyo Ghoul", "slug": "tokyo-ghoul"},
        {"titulo": "Yamishibai", "slug": "yamishibai-japanese-ghost-stories"},
        {"titulo": "Umineko", "slug": "umineko-no-naku-koro-ni"},
        {"titulo": "Boogiepop wa Warawanai", "slug": "boogiepop-wa-warawanai-2019"},
        {"titulo": "Magical Girl Site", "slug": "mahou-shoujo-site"},
        {"titulo": "Junji Ito Collection", "slug": "junji-ito-collection"},
    ],
    "fantasia": [
        {"titulo": "Re:Zero", "slug": "re-zero-kara-hajimeru-isekai-seikatsu"},
        {"titulo": "Sword Art Online", "slug": "sword-art-online"},
        {"titulo": "Overlord", "slug": "overlord"},
        {"titulo": "That Time I Got Reincarnated as a Slime", "slug": "tensei-shitara-slime-datta-ken"},
        {"titulo": "No Game No Life", "slug": "no-game-no-life"},
        {"titulo": "KonoSuba", "slug": "kono-subarashii-sekai-ni-shukufuku-wo"},
        {"titulo": "Made in Abyss", "slug": "made-in-abyss"},
        {"titulo": "Violet Evergarden", "slug": "violet-evergarden"},
        {"titulo": "Fullmetal Alchemist Brotherhood", "slug": "fullmetal-alchemist-brotherhood"},
        {"titulo": "Mushishi", "slug": "mushishi"},
        {"titulo": "The Rising of the Shield Hero", "slug": "tate-no-yuusha-no-nariagari"},
        {"titulo": "Log Horizon", "slug": "log-horizon"},
        {"titulo": "Mahou Shoujo Madoka Magica", "slug": "mahou-shoujo-madoka-magica"},
        {"titulo": "Fate/Zero", "slug": "fate-zero"},
        {"titulo": "Fate/Stay Night UBW", "slug": "fate-stay-night-unlimited-blade-works"},
        {"titulo": "Spirited Away (Ghibli)", "slug": "sen-to-chihiro-no-kamikakushi"},
        {"titulo": "Howl's Moving Castle", "slug": "howl-no-ugoku-shiro"},
        {"titulo": "Nausicaa", "slug": "kaze-no-tani-no-nausicaa"},
        {"titulo": "Princess Mononoke", "slug": "mononoke-hime"},
        {"titulo": "Black Clover", "slug": "black-clover"},
    ],
    "shounen": [
        {"titulo": "Naruto", "slug": "naruto-clasico"},
        {"titulo": "Naruto Shippuden", "slug": "naruto-shippuden"},
        {"titulo": "One Piece", "slug": "one-piece"},
        {"titulo": "Bleach", "slug": "bleach"},
        {"titulo": "Dragon Ball Z", "slug": "dragon-ball-z"},
        {"titulo": "My Hero Academia", "slug": "boku-no-hero-academia"},
        {"titulo": "Demon Slayer", "slug": "kimetsu-no-yaiba"},
        {"titulo": "Jujutsu Kaisen", "slug": "jujutsu-kaisen"},
        {"titulo": "Fairy Tail", "slug": "fairy-tail"},
        {"titulo": "Hunter x Hunter", "slug": "hunter-x-hunter-2011"},
        {"titulo": "Black Clover", "slug": "black-clover"},
        {"titulo": "Haikyuu", "slug": "haikyuu"},
        {"titulo": "Kuroko no Basket", "slug": "kuroko-no-basket"},
        {"titulo": "Fullmetal Alchemist Brotherhood", "slug": "fullmetal-alchemist-brotherhood"},
        {"titulo": "Blue Exorcist", "slug": "ao-no-exorcist"},
        {"titulo": "Assassination Classroom", "slug": "ansatsu-kyoushitsu"},
        {"titulo": "Noragami", "slug": "noragami"},
        {"titulo": "Soul Eater", "slug": "soul-eater"},
        {"titulo": "D.Gray-man", "slug": "d-gray-man"},
        {"titulo": "Katekyo Hitman Reborn", "slug": "katekyo-hitman-reborn"},
    ],
    "seinen": [
        {"titulo": "Berserk", "slug": "berserk-1997"},
        {"titulo": "Vinland Saga", "slug": "vinland-saga"},
        {"titulo": "Tokyo Ghoul", "slug": "tokyo-ghoul"},
        {"titulo": "Parasyte", "slug": "kiseijuu-sei-no-kakuritsu"},
        {"titulo": "Mushishi", "slug": "mushishi"},
        {"titulo": "Hellsing Ultimate", "slug": "hellsing-ultimate"},
        {"titulo": "Made in Abyss", "slug": "made-in-abyss"},
        {"titulo": "Chainsaw Man", "slug": "chainsaw-man"},
        {"titulo": "Dorohedoro", "slug": "dorohedoro"},
        {"titulo": "91 Days", "slug": "91-days"},
        {"titulo": "Gangsta", "slug": "gangsta"},
        {"titulo": "Moriarty the Patriot", "slug": "yuukoku-no-moriarty"},
        {"titulo": "Golden Kamuy", "slug": "golden-kamuy"},
        {"titulo": "Blade of the Immortal", "slug": "mugen-no-juunin-immortal"},
        {"titulo": "Banana Fish", "slug": "banana-fish"},
    ],
    "shoujo": [
        {"titulo": "Sailor Moon", "slug": "bishoujo-senshi-sailor-moon"},
        {"titulo": "Fruits Basket", "slug": "fruits-basket-2019"},
        {"titulo": "Cardcaptor Sakura", "slug": "cardcaptor-sakura"},
        {"titulo": "Ouran High School Host Club", "slug": "ouran-koukou-host-club"},
        {"titulo": "Akatsuki no Yona", "slug": "akatsuki-no-yona"},
        {"titulo": "Kimi ni Todoke", "slug": "kimi-ni-todoke"},
        {"titulo": "Ao Haru Ride", "slug": "ao-haru-ride"},
        {"titulo": "Nana", "slug": "nana"},
        {"titulo": "Vampire Knight", "slug": "vampire-knight"},
        {"titulo": "Lovely Complex", "slug": "lovely-complex"},
        {"titulo": "Skip Beat", "slug": "skip-beat"},
        {"titulo": "Say I Love You", "slug": "sukitte-ii-na-yo"},
        {"titulo": "Wolf Girl and Black Prince", "slug": "ookami-shoujo-to-kuro-ouji"},
        {"titulo": "Kaichou wa Maid-sama", "slug": "kaichou-wa-maid-sama"},
        {"titulo": "Gekkan Shoujo Nozaki-kun", "slug": "gekkan-shoujo-nozaki-kun"},
    ],
    "yuri": [
        {"titulo": "Bloom Into You", "slug": "yagate-kimi-ni-naru"},
        {"titulo": "Citrus", "slug": "citrus"},
        {"titulo": "Sakura Trick", "slug": "sakura-trick"},
        {"titulo": "Yuru Yuri", "slug": "yuru-yuri"},
        {"titulo": "Strawberry Panic", "slug": "strawberry-panic"},
        {"titulo": "Kannazuki no Miko", "slug": "kannazuki-no-miko"},
        {"titulo": "Maria-sama ga Miteru", "slug": "maria-sama-ga-miteru"},
        {"titulo": "Shoujo Kageki Revue Starlight", "slug": "shoujo-kageki-revue-starlight"},
        {"titulo": "Adachi to Shimamura", "slug": "adachi-to-shimamura"},
        {"titulo": "NieR:Automata Ver1.1a", "slug": "nier-automata-ver1-1a"},
        {"titulo": "Yuuki Yuuna wa Yuusha de Aru", "slug": "yuuki-yuuna-wa-yuusha-de-aru"},
        {"titulo": "PuraOre! Pride of Orange", "slug": "puraore-pride-of-orange"},
        {"titulo": "Hina Logic", "slug": "hina-logic-from-luck-logic"},
        {"titulo": "Asagao to Kase-san", "slug": "asagao-to-kase-san"},
        {"titulo": "Konohana Kitan", "slug": "konohana-kitan"},
    ],
    "ecchi": [
        {"titulo": "High School DxD", "slug": "high-school-dxd"},
        {"titulo": "Highschool of the Dead", "slug": "gakuen-mokushiroku-high-school-of-the-dead"},
        {"titulo": "To LOVE-Ru", "slug": "to-love-ru"},
        {"titulo": "Monster Musume", "slug": "monster-musume-no-iru-nichijou"},
        {"titulo": "Prison School", "slug": "prison-school"},
        {"titulo": "Shimoneta", "slug": "shimoneta-to-iu-gainen-ga-sonzai-shinai-taikutsu-na-sekai"},
        {"titulo": "Sekirei", "slug": "sekirei"},
        {"titulo": "Rosario + Vampire", "slug": "rosario-to-vampire"},
        {"titulo": "Haganai", "slug": "boku-wa-tomodachi-ga-sukunai"},
        {"titulo": "Infinite Stratos", "slug": "is-infinite-stratos"},
    ],
    "psicologico": [
        {"titulo": "Death Note", "slug": "death-note"},
        {"titulo": "Code Geass", "slug": "code-geass-hangyaku-no-lelouch"},
        {"titulo": "Neon Genesis Evangelion", "slug": "shinseiki-evangelion"},
        {"titulo": "Madoka Magica", "slug": "mahou-shoujo-madoka-magica"},
        {"titulo": "Steins;Gate", "slug": "steins-gate"},
        {"titulo": "Monster", "slug": "monster"},
        {"titulo": "Paranoia Agent", "slug": "mousou-dairinin"},
        {"titulo": "Serial Experiments Lain", "slug": "serial-experiments-lain"},
        {"titulo": "Promised Neverland", "slug": "yakusoku-no-neverland"},
        {"titulo": "Classroom of the Elite", "slug": "youkoso-jitsuryoku-shijou-shugi-no-kyoushitsu-e"},
        {"titulo": "Talentless Nana", "slug": "munou-na-nana"},
        {"titulo": "ID: Invaded", "slug": "id-invaded"},
        {"titulo": "Vanitas no Carte", "slug": "vanitas-no-carte"},
        {"titulo": "Higurashi", "slug": "higurashi-no-naku-koro-ni"},
        {"titulo": "Umineko", "slug": "umineko-no-naku-koro-ni"},
    ],
    "deportes": [
        {"titulo": "Haikyuu", "slug": "haikyuu"},
        {"titulo": "Kuroko no Basket", "slug": "kuroko-no-basket"},
        {"titulo": "Hajime no Ippo", "slug": "hajime-no-ippo"},
        {"titulo": "Yuri on Ice", "slug": "yuri-on-ice"},
        {"titulo": "Free!", "slug": "free"},
        {"titulo": "Prince of Tennis", "slug": "tennis-no-ouji-sama"},
        {"titulo": "Slam Dunk", "slug": "slam-dunk"},
        {"titulo": "Major", "slug": "major"},
        {"titulo": "Eyeshield 21", "slug": "eyeshield-21"},
        {"titulo": "Inazuma Eleven", "slug": "inazuma-eleven"},
        {"titulo": "Daiya no Ace", "slug": "daiya-no-ace"},
        {"titulo": "Chihayafuru", "slug": "chihayafuru"},
        {"titulo": "Run with the Wind", "slug": "kaze-ga-tsuyoku-fuiteiru"},
        {"titulo": "Ping Pong the Animation", "slug": "ping-pong-the-animation"},
        {"titulo": "Baby Steps", "slug": "baby-steps"},
    ],
}

GENEROS_CATALOGO = list(CATALOGO.keys())
